name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        node: ["20", "22"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # - name: Publish to npm if needed
      #   if: github.ref == 'refs/heads/main' && matrix.node == '22'
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npm publish
